version: "3"

services:

  node:
    build:
      context: ./docker/node
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./server.js:/app/server.js

  caddy:
    build:
      context: ./docker/caddy
    restart: unless-stopped
    depends_on:
      - node
      - nextjs
    command: [ "caddy", "run", "--resume" ]
    ports:
      - "80:80"
      - "2019:2019"
    volumes:
      - ./docker/caddy/autosave.json:/config/caddy/autosave.json

  nextjs:
    build:
      context: ./docker/nextjs
    ports:
      - 3001:3001
    depends_on:
      - node
    stdin_open: true
    volumes:
      - ./nextjs:/app