# Base on offical Node.js Alpine image
FROM node:18.1-alpine

# Set working directory
WORKDIR /app

# Expose the listening port
EXPOSE 3000

# Run npm start script when container starts
CMD [ "node", "server.js" ]